# Generated by Django 4.1 on 2022-08-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_visitor_is_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='visitor',
        ),
        migrations.AddField(
            model_name='visitor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
