# Generated by Django 4.0.7 on 2022-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_location_visitor_visitor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
